Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/**/*
    - config/**/**/*
    - Gemfile
    - Gemfile.lock
